service: todo-service

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-iam-roles-per-function

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
     - dev
     - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  region: sa-east-1

  environment:
    TODO_TABLE_NAME: todos
    IX_TODO_USER_ID: ix_todos_by-user

functions:
  createTodo:
    handler: src/functions/todo/create/handler.main
    events:
      - http:
          path: /todos/{userId}
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODO_TABLE_NAME}
  getTodosByUserID:
    handler: src/functions/todo/getByUser/handler.main
    events:
      - http:
          path: /todos/{userId}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODO_TABLE_NAME}/index/${self:provider.environment.IX_TODO_USER_ID}

resources:
  Resources:
    dbTODOS:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODO_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.IX_TODO_USER_ID}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
